S0Log/SOLog-FE

src/App.jsx, src/components/IndexPage/IndexPage.jsx
- 전반적인 폴더 구조 잡기
- #1 
- 전반적인 폴더 구조
=> feat/#1 전반적인 폴더 구조 잡기

src/components/MainPage/Chart.jsx, src/components/Search.jsx
- index page dev 검색 바 연한 선 해결
- #3 
- 연한 선 있는 거 이슈 해결
=> index page dev 검색 바 연한 선 해결

src/components/MainPage/CompanyInfoPage/CompanyInfoPage.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CompanyInfoPage1.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CompanyIntro.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CurrentPrice.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/StockPriceImg.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardLeft.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardRight.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CompanyInfoPage2.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage3/CompanyInfoPage3.jsx, tailwind.config.js
- feat/#15company_info_page_layout 합치기
- #15
=> feat/#15company_info_page_layout 합치기

package-lock.json, package.json, src/App.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardLeft.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardRight.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CompanyInfoPage2.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage3/CompanyInfoPage3.jsx, src/components/MainPage/SideBar.jsx, src/components/MainPage/UpSideBar.jsx, src/main.jsx, src/routers/main-router.jsx
- company_info_page 2,3 레이아웃 잡음
- #21
- company_info_page
=> feat/#21 company_info_page 2,3 레이아웃 잡음

src/components/MainPage/AnalyzeChartPage/AnalyzeChart.jsx, src/components/MainPage/AnalyzeChartPage/AnalyzeChartPage.jsx, src/components/MainPage/AnalyzeChartPage/DurationSelectBar.jsx, src/components/MainPage/AnalyzeChartPage/TotalInfo.jsx, src/components/MainPage/CompanyDetailPage/CompanyDetailPage.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage.jsx, src/components/MainPage/SideBar.jsx, src/components/MainPage/UpSideBar.jsx, src/routes/layout.jsx
- 전반적인 구조 잡기 차트분석페이지 세부적인 레이아웃은 다시 잡아야함
- #23
- css
- 차트분석페이지
=> feat/#23 전반적인 구조 잡기 차트분석페이지 세부적인 레이아웃은 다시 잡아야함 by지원

index.html, src/components/IndexPage/RecommendedStocks.jsx, src/components/Search.jsx
- bootstrap 프레임워크 추가로 변경된 Search.jsx의 css를 되돌려놓음
- #26 
- 부트스트랩 파일 설치로 적용된 CSS를 tailwind css 클래스명 추가로 되돌려 놓음
=> Search.jsx CSS 편집

src/components/MainPage/CompanyDetailPage/CompanyDetail.jsx, src/components/MainPage/CompanyDetailPage/CompanyDetailChart.jsx, src/components/MainPage/CompanyDetailPage/CompanyDetailPage.jsx, src/components/MainPage/PastComparePage/Calendar.jsx, src/components/MainPage/PastComparePage/ComparePage.jsx, src/components/MainPage/PastComparePage/PastArticle.jsx, src/components/MainPage/PastComparePage/PastCompareInfos.jsx, src/components/MainPage/PastComparePage/PastComparePage.jsx, src/components/MainPage/PastComparePage/PastPage.jsx, src/components/MainPage/PastComparePage/TermSelect.jsx, src/index.css
- pastcomparepage 레이아웃 잡기
- 과거비교 페이지 레이아웃 구현
- 러프하게 페이지 레이아웃 잡음
=> pastcomparepage 레이아웃 잡기

src/components/Search.jsx
-검색 기능 개선
- #38 
- toLowerCase() 추가하여 영문 포함 기업명 대소문자 구분 없이 검색 가능하게 함
=> toLowerCase() 추가

tailwind.config.js
=> tailwind.config.js 파일 수정

tailwind.config.js
=> main brach 로 merge

nginx.conf
- nginx.conf app -> solog_be
- nginx.conf 내용 컨테이너 이름으로 변경
=> fix: nginx.conf app -> solog_be

package-lock.json, package.json, src/components/IndexPage/RecommendedStocks.jsx, src/components/MainPage/CompanyDetailPage/CompanyDetail.jsx, src/components/MainPage/SideBar.jsx, src/index.css, yarn.lock
- 기업상세 테이블 선 제거 및 툴팁 디자인 완성
- #67 
- 기업상세 테이블 선 제거
- react tooltip 활용하여 툴팁 디자인 완성
- 툴팁 내용 정리 -> 향후 서버에 반영 예정
=> 기업상세 테이블 선 제거 및 툴팁 디자인 완성

src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CompanyIntro.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CurrentPrice.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardLeft.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardRight.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage3/CompanyInfoPage3.jsx
- 기업정보 페이지 useContext 수정
- #70 
- useContext 사용
=> 기업정보 페이지 useContext 수정

src/components/MainPage/CompanyDetailPage/CompanyDetail.jsx
- tooltip 내용 html코드로 인식되게 변경
- #76 
- tooltip data-tooltip-html 속성 활용
=> tooltip 내용 html코드로 인식되게 변경

src/index.css
- index.css 수정 반영
- #78 작업 중
- index.css 수정사항 반영
=> index.css 수정 반영

src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/StockPriceImg.jsx
- 기업정보 페이지 차트 라이브러리 활용해서 api 연결
- #78 
- Apex Charts 활용해서 기업정보 페이지 차트 api 연결
=> 기업정보 페이지 차트 라이브러리 활용해서 api 연결

src/components/MainPage/AnalyzeChartPage/AnalyzeChart.jsx, src/components/MainPage/AnalyzeChartPage/AnalyzeChartPage.jsx, src/components/MainPage/AnalyzeChartPage/CompanySummaryInfo.jsx, src/components/MainPage/AnalyzeChartPage/TotalInfo.jsx
- 기업요약 api 연결
- #80 
- 클릭된 봉의 durationType과 date를 props로 전달해 차트분석 페이지 기업요약 api 연결
=> 기업요약 api 연결

src/components/MainPage/AnalyzeChartPage/CompanySummaryInfo.jsx, src/components/MainPage/AnalyzeChartPage/PastInfos.jsx, src/components/MainPage/AnalyzeChartPage/TotalInfo.jsx
- 리포트 api 연결
- #81 
- 리포트 api 연결해서 title, url 적용
=> 리포트 api 연결

src/components/MainPage/AnalyzeChartPage/PastInfos.jsx
- 리포트 최신 5개만 렌더링
- #85
- slice(0,5) 활용해서 배열 자르기
=> 리포트 최신 5개만 렌더링

package-lock.json, package.json, src/components/MainPage/AnalyzeChartPage/CompanySummaryInfo.jsx, src/components/MainPage/AnalyzeChartPage/PastInfos.jsx, src/components/MainPage/DurationSelectBar.css, src/index.css, tailwind.config.js, yarn.lock
- 뉴스 및 리포트 iframe 구현
- #88 
- 뉴스와 리포트의 url 활용해서 iframe을 띄워주는 모달창 구현
=> 뉴스 및 리포트 iframe 구현

src/components/MainPage/PastComparePage/PastPage.jsx
- 과거비교 페이지 PastPage.jsx 검색 버튼 추가
- #91 
- 
- button 태그 추가
- 날짜 선택/기간 선택 - 검색 순으로 나열
=> 과거비교 페이지 PastPage.jsx 검색 버튼 추가

src/components/MainPage/PastComparePage/Calendar.jsx, src/components/MainPage/PastComparePage/PastPage.jsx, src/components/MainPage/SideBar.jsx, src/index.css
- Calendar CSS 수정
- #92 
- Calendar CSS 수정 위해 index.css에 내용 추가
=> Calendar CSS 수정

src/components/MainPage/AnalyzeChartPage/PastInfos.jsx
- 이베스트투자증권 -> 이베스트증권
- 이베스트투자증권 -> 이베스트증권
- 
- 리서치 writer와 동일하게 이름 수정
=> 이베스트투자증권 -> 이베스트증권

package-lock.json, package.json, src/components/MainPage/AnalyzeChartPage/PastInfos.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage1/CurrentPrice.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardLeft.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage2/CardRight.jsx, src/components/MainPage/CompanyInfoPage/CompanyInfoPage3/CompanyInfoPage3.jsx, src/components/MainPage/SideBar.jsx, src/components/Search.jsx, src/index.css, yarn.lock
- 기업정보 UI 최종 커밋
- #95 
- ApexCharts 라이브러리 활용
=> 기업정보 UI 최종 커밋

nginx.conf
- daum관련 CORS 에러 해결
- nginx에서 cors 에러 해결
=> daum관련 CORS 에러 해결 (nginx.conf)

nginx.conf
- hotfix: nginx.conf
- nginx.conf 오류 해결
=> hotfix: nginx.conf

src/components/MainPage/PastComparePage/Calendar.jsx, src/components/Search.jsx
- 캘린더 날짜 클릭된 경우 에러 수정 및 검색창 이슈 해결
- 마이너한 이슈 해결
- ISO date 사용된 함수 수정
- 검색 결과 클릭 시 검색창에 반영 안되는 이슈 해결
=> 캘린더 날짜 클릭된 경우 에러 수정 및 검색창 이슈 해결
